/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BancoDadosJFrame.java
 *
 * Created on 30/01/2012, 22:09:21
 */
package com.easytest.gui;

import com.easytest.files.DataManager;
import com.easytest.files.exception.ReportTestException;
import com.easytest.gui.listener.BancoDadosActionListener;
import com.easytest.model.dao.BancoDadosDao;
import com.easytest.model.vo.BancoDados;
import com.easytest.model.vo.Projeto;
import javax.swing.JOptionPane;

/**
 *
 * @author gilberto
 */
public class BancoDadosJFrame extends javax.swing.JFrame {

    /** Creates new form BancoDadosJFrame */
    public BancoDadosJFrame() {
        initComponents();
        //busca as informações gravadas e alimenta o formulário do cadastro
        initValues();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        driverClassJLabel = new javax.swing.JLabel();
        connectionUrlJLabel = new javax.swing.JLabel();
        userJLabel = new javax.swing.JLabel();
        passJLabel = new javax.swing.JLabel();
        driverClassJTextField = new javax.swing.JTextField();
        connectionUrlJTextField = new javax.swing.JTextField();
        userJTextField = new javax.swing.JTextField();
        passJTextField = new javax.swing.JTextField();
        buttonsJPanel = new javax.swing.JPanel();
        gravarJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuração do banco de dados");
        setResizable(false);

        driverClassJLabel.setText("Driver Class:");

        connectionUrlJLabel.setText("Connection URL:");

        userJLabel.setText("User:");

        passJLabel.setText("Password:");

        driverClassJTextField.setText("com.sybase.jdbc3.jdbc.SybDriver");

        connectionUrlJTextField.setText("jdbc:sybase:Tds:localhost:50505");

        userJTextField.setText("dba");

        passJTextField.setText("sql");

        buttonsJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        gravarJButton.setText("Gravar");
        gravarJButton.setActionCommand("gravar");
        gravarJButton.addActionListener(listener);

        javax.swing.GroupLayout buttonsJPanelLayout = new javax.swing.GroupLayout(buttonsJPanel);
        buttonsJPanel.setLayout(buttonsJPanelLayout);
        buttonsJPanelLayout.setHorizontalGroup(
            buttonsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gravarJButton)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        buttonsJPanelLayout.setVerticalGroup(
            buttonsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gravarJButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(driverClassJLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(connectionUrlJLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userJLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passJLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passJTextField)
                            .addComponent(userJTextField)
                            .addComponent(connectionUrlJTextField)
                            .addComponent(driverClassJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buttonsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driverClassJLabel)
                    .addComponent(driverClassJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectionUrlJLabel)
                    .addComponent(connectionUrlJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userJLabel)
                    .addComponent(userJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passJLabel)
                    .addComponent(passJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
    
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new BancoDadosJFrame().setVisible(true);
    }
    });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsJPanel;
    private javax.swing.JLabel connectionUrlJLabel;
    private javax.swing.JTextField connectionUrlJTextField;
    private javax.swing.JLabel driverClassJLabel;
    private javax.swing.JTextField driverClassJTextField;
    private javax.swing.JButton gravarJButton;
    private javax.swing.JLabel passJLabel;
    private javax.swing.JTextField passJTextField;
    private javax.swing.JLabel userJLabel;
    private javax.swing.JTextField userJTextField;
    // End of variables declaration//GEN-END:variables
    private BancoDadosActionListener listener = new BancoDadosActionListener(this);
    private BancoDadosDao dao = new BancoDadosDao();
    private Integer iProjeto;

    public final void initValues() {
        try {
            BancoDados banco = dao.getBancoDados(DataManager.getInstance().getProjeto().getIProjeto());
            if (banco != null) {
                connectionUrlJTextField.setText(banco.getConnectionUrl());
                driverClassJTextField.setText(banco.getDriverClass());
                passJTextField.setText(banco.getPass());
                userJTextField.setText(banco.getUser());
                iProjeto = banco.getIProjeto();
            }
        } catch (ReportTestException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), this.getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }

    public final BancoDados getBancoDados() {
        BancoDados banco = new BancoDados();

        //transfere os dados da visão para o vo
        banco.setIProjeto(iProjeto);
        banco.setConnectionUrl(connectionUrlJTextField.getText());
        banco.setDriverClass(driverClassJTextField.getText());
        banco.setPass(passJTextField.getText());
        banco.setUser(userJTextField.getText());

        return banco;
    }
}
