/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfiguracaoJFrame.java
 *
 * Created on 30/01/2012, 22:51:12
 */
package com.easytest.gui;

import com.easytest.files.DataManager;
import com.easytest.files.exception.ReportTestException;
import com.easytest.gui.listener.ConfiguracaoActionListener;
import com.easytest.model.dao.ProjetoDao;
import com.easytest.model.vo.Projeto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author gilberto
 */
public class ConfiguracaoJFrame extends javax.swing.JFrame {

    /** Creates new form ConfiguracaoJFrame */
    public ConfiguracaoJFrame(PrincipalJFrame framePrincipal) {
        this.framePrincipal = framePrincipal;
        //inicializa o listener quando o método construtor for chamado
        if (listener == null) {
            listener = new ConfiguracaoActionListener(this, framePrincipal);
        }
        initComponents();
        initValues();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        reportsJLabel = new javax.swing.JLabel();
        nomeProjetoJLabel = new javax.swing.JLabel();
        nomeProjetoJTextField = new javax.swing.JTextField();
        reportsJTextField = new javax.swing.JTextField();
        buttonsJPanel = new javax.swing.JPanel();
        gravarJButton = new javax.swing.JButton();
        novoJButton = new javax.swing.JButton();
        excluirJButton = new javax.swing.JButton();
        selecionarArquivoReportJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoJTextArea = new javax.swing.JTextArea();
        descricaoJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        projetosJTable = new javax.swing.JTable();
        ativoJCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuração do projeto");
        setResizable(false);

        reportsJLabel.setText("Reports:");

        nomeProjetoJLabel.setText("Nome do projeto:");

        buttonsJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        gravarJButton.setText("Gravar");
        gravarJButton.setActionCommand("gravar");
        gravarJButton.addActionListener(listener);

        novoJButton.setText("Novo");
        novoJButton.setActionCommand("novo");
        novoJButton.addActionListener(listener);

        excluirJButton.setText("Excluir");
        excluirJButton.setActionCommand("excluir");
        excluirJButton.addActionListener(listener);

        javax.swing.GroupLayout buttonsJPanelLayout = new javax.swing.GroupLayout(buttonsJPanel);
        buttonsJPanel.setLayout(buttonsJPanelLayout);
        buttonsJPanelLayout.setHorizontalGroup(
            buttonsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(novoJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gravarJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirJButton)
                .addContainerGap(460, Short.MAX_VALUE))
        );
        buttonsJPanelLayout.setVerticalGroup(
            buttonsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gravarJButton)
                    .addComponent(novoJButton)
                    .addComponent(excluirJButton))
                .addContainerGap())
        );

        selecionarArquivoReportJButton.setText("...");
        selecionarArquivoReportJButton.setActionCommand("selecionarArquivoReport");
        selecionarArquivoReportJButton.addActionListener(listener);

        descricaoJTextArea.setColumns(20);
        descricaoJTextArea.setRows(5);
        jScrollPane1.setViewportView(descricaoJTextArea);

        descricaoJLabel.setText("Descrição");

        projetosJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Ativo"
            }
        ));
        projetosJTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        projetosJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projetosJTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(projetosJTable);

        ativoJCheckBox.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeProjetoJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeProjetoJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reportsJLabel)
                    .addComponent(descricaoJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(reportsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionarArquivoReportJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(ativoJCheckBox)
                        .addGap(23, 23, 23))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeProjetoJLabel)
                    .addComponent(nomeProjetoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descricaoJLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecionarArquivoReportJButton)
                    .addComponent(reportsJLabel)
                    .addComponent(ativoJCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projetosJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projetosJTableMouseClicked

        int rowSelect = projetosJTable.getSelectedRow();

        if (rowSelect >= 0) {
            Integer codigo = (Integer) projetosJTable.getModel().getValueAt(rowSelect, 0);
            try {
                Projeto p = dao.getProjeto(codigo);

                if (p == null) {
                    throw new ReportTestException("O projeto selecionado não foi encontrado!");
                }
                setProjeto(p);
            } catch (ReportTestException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), this.getTitle(), JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_projetosJTableMouseClicked
    /**
     * @param args the command line arguments
    
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new ConfiguracaoJFrame().setVisible(true);
    }
    });
    }
     * */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ativoJCheckBox;
    private javax.swing.JPanel buttonsJPanel;
    private javax.swing.JLabel descricaoJLabel;
    private javax.swing.JTextArea descricaoJTextArea;
    private javax.swing.JButton excluirJButton;
    private javax.swing.JButton gravarJButton;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nomeProjetoJLabel;
    private javax.swing.JTextField nomeProjetoJTextField;
    private javax.swing.JButton novoJButton;
    private javax.swing.JTable projetosJTable;
    private javax.swing.JLabel reportsJLabel;
    private javax.swing.JTextField reportsJTextField;
    private javax.swing.JButton selecionarArquivoReportJButton;
    // End of variables declaration//GEN-END:variables
    //configurações específicas do projeto
    private PrincipalJFrame framePrincipal;
    private ConfiguracaoActionListener listener;
    private ProjetoDao dao = new ProjetoDao();
    private Integer iProjeto;   //código corrente do projeto

    //limpa os campos da tela
    public void clearForm() {
        nomeProjetoJTextField.setText("");
        reportsJTextField.setText("");
        descricaoJTextArea.setText("");
        iProjeto = null;
        ativoJCheckBox.setSelected(false);
    }

    public void setProjeto(Projeto p) {
        nomeProjetoJTextField.setText(p.getNome());
        reportsJTextField.setText(p.getReport());
        descricaoJTextArea.setText(p.getDescricao());
        iProjeto = p.getIProjeto();

        //verifica se é projeto principal
        if (p.getAtivo() != null && "S".equals(p.getAtivo())) {
            ativoJCheckBox.setSelected(true);
        } else {
            ativoJCheckBox.setSelected(false);
        }
    }

    public Projeto getProjeto() {
        Projeto p = new Projeto();
        p.setIProjeto(iProjeto);
        p.setNome(nomeProjetoJTextField.getText());
        p.setDescricao(descricaoJTextArea.getText());
        p.setReport(reportsJTextField.getText());
        if (ativoJCheckBox.isSelected()) {
            p.setAtivo("S");
        } else {
            p.setAtivo(null);
        }

        return p;
    }

    public final void initValues() {
        clearForm();

        //busca todos os projetos do banco de dados e adiciona no JTable
        try {
            List<Projeto> pList = dao.getAllProjeto();
            Object[][] dadosTabela = new Object[pList.size()][3];
            for (int i = 0; i < pList.size(); i++) {
                Projeto p = pList.get(i);
                dadosTabela[i][0] = p.getIProjeto();
                dadosTabela[i][1] = p.getNome();

                //verifica se é projeto principal
                if (p.getAtivo() != null && "S".equals(p.getAtivo())) {
                    dadosTabela[i][2] = "Sim";

                    //seta o projeto corrente
                    DataManager.getInstance().setProjeto(p);
                } else {
                    dadosTabela[i][2] = "Não";
                }
            }

            //passa os dados para a tabela
            projetosJTable.setModel(new javax.swing.table.DefaultTableModel(
                    dadosTabela,
                    new String[]{
                        "Codigo", "Nome", "Ativo"
                    }));


        } catch (ReportTestException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), this.getTitle(), JOptionPane.ERROR_MESSAGE);
        }
    }

    public JTextField getNomeProjetoJTextField() {
        return nomeProjetoJTextField;
    }

    public JTextField getReportsJTextField() {
        return reportsJTextField;
    }
}
