/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditorScriptJFrame.java
 *
 * Created on 28/01/2012, 19:57:19
 */
package com.easytest.gui;

import com.easytest.model.vo.TestCase;
import com.easytest.gui.listener.EditorScriptActionListener;
import net.boplicity.xmleditor.XmlEditorKit;

/**
 *
 * @author gilberto
 */
public class EditorScriptJFrame extends javax.swing.JFrame {

    /** Creates new form EditorScriptJFrame */
    public EditorScriptJFrame(TestCase testCase) {
        //deve ser executado somente depois, caso contrário o listener será null e os action não fucionarão
        initComponents();
        //text/xml
        listener.addCurrentCasoTeste(testCase);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        editorScriptPane = new javax.swing.JEditorPane();
        buttosPanel = new javax.swing.JPanel();
        gravarJButton = new javax.swing.JButton();
        fecharJButton = new javax.swing.JButton();
        editarParametrosJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editor de Script");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        editorScriptPane.setContentType("text/xml");
        editorScriptPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editorScriptPane.setEditorKit(new XmlEditorKit());
        jScrollPane1.setViewportView(editorScriptPane);

        gravarJButton.setText("Gravar");

        fecharJButton.setText("Fechar");

        editarParametrosJButton.setText("Editar Parâmetros");

        javax.swing.GroupLayout buttosPanelLayout = new javax.swing.GroupLayout(buttosPanel);
        buttosPanel.setLayout(buttosPanelLayout);
        buttosPanelLayout.setHorizontalGroup(
            buttosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttosPanelLayout.createSequentialGroup()
                .addComponent(gravarJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecharJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarParametrosJButton)
                .addContainerGap(501, Short.MAX_VALUE))
        );
        buttosPanelLayout.setVerticalGroup(
            buttosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(gravarJButton)
                .addComponent(fecharJButton)
                .addComponent(editarParametrosJButton))
        );

        gravarJButton.setActionCommand("gravar");
        gravarJButton.addActionListener(listener);
        fecharJButton.setActionCommand("fechar");
        fecharJButton.addActionListener(listener);
        editarParametrosJButton.setActionCommand("editarParametros");
        editarParametrosJButton.addActionListener(listener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addComponent(buttosPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttosPanel;
    private javax.swing.JButton editarParametrosJButton;
    private javax.swing.JEditorPane editorScriptPane;
    private javax.swing.JButton fecharJButton;
    private javax.swing.JButton gravarJButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    //implementação manual para controle da aplicação
    private EditorScriptActionListener listener = new EditorScriptActionListener(this);

    public javax.swing.JEditorPane getEditorScriptPane() {
        return editorScriptPane;

    }
}
